### ISSUE TITLE
Erro Branch 3.1 dev

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#123]
> ImportError: No module named qgscollapsiblegroupbox 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 333, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\__init__.py", line 34, in classFactory
    from .dsg_tools import DsgTools
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\dsg_tools.py", line 42, in 
    from DsgTools.ServerTools.batchDbManager import BatchDbManager
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ServerTools\batchDbManager.py", line 46, in 
    os.path.dirname(__file__), 'batchDbManager.ui'))
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 244, in 
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\CustomWidgets\fieldToolBoxConfigManagerWidget.py", line 34, in 
    from DsgTools.ProductionTools.FieldToolBox.field_setup import FieldSetup
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ProductionTools\FieldToolBox\field_setup.py", line 42, in 
    os.path.dirname(__file__), 'field_setup.ui'))
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 161, in 
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\CustomWidgets\buttonPropWidget.py", line 35, in 
    os.path.dirname(__file__), 'buttonPropWidget.ui'))
  File "C:\OSGEO4~1\apps\Python27\lib\site-packages\PyQt4\uic\__init__.py", line 213, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 74, in 
  File "C:/OSGEO4~1/apps/qgis/./python\qgis\utils.py", line 607, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: No module named qgscollapsiblegroupbox

Erro no QGIS 2.18.12.

**Comment by phborba** [comment]
resolvido no commit 39e4436983a82f1e92e5c9dd0377f5ed2fe86804

Testa ae pra mim por favor @dinizime

**Comment by dinizime** [comment]
Resolvido
