### ISSUE TITLE
Erro python ao selecionar camada branch 3.1_dev

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#148]
### Subject of the issue (Assunto do problema)
O seguinte erro python ocorre a selecionar uma feição que tenha um campo Relatorio Reference

```
An error has occurred while executing Python code: 
TypeError: arguments did not match any overloaded call:   QTableWidgetItem(int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'   QTableWidgetItem(QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'   QTableWidgetItem(QIcon, QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'   QTableWidgetItem(QTableWidgetItem): argument 1 has unexpected type 'list' 
Traceback (most recent call last):
  File "C:/Users/diniz/.qgis2/python/plugins\DsgTools\AttributeTools\code_list.py", line 138, in on_comboBox_currentIndexChanged
    self.loadCodeList()
  File "C:/Users/diniz/.qgis2/python/plugins\DsgTools\AttributeTools\code_list.py", line 160, in loadCodeList
    codeItem = QTableWidgetItem(code)
TypeError: arguments did not match any overloaded call:
  QTableWidgetItem(int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'
  QTableWidgetItem(QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'
  QTableWidgetItem(QIcon, QString, int type=QTableWidgetItem.Type): argument 1 has unexpected type 'list'
  QTableWidgetItem(QTableWidgetItem): argument 1 has unexpected type 'list'
```

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional): Windows 7
* version of QGIS (Versão do QGIS):  2.18.11
* version of DSGTools (Versão do DSGTools): 3.1 dev

### Steps to reproduce (Passos para reproduzir)
Selecionar uma camada que possua atributo do tipo Relation Reference.

**Comment by phborba** [comment]
Foi com aquele tipo de widget novo que você está usando da sumarizada?

**Comment by dinizime** [comment]
Sim, utilizando o Relation Reference, widget nativo do QGIS.

**Comment by phborba** [comment]
Primeiro passo foi deixar o widget fazer nada no Relation Reference. Criado issue #155 para tratar disso. Fechando por ter sanado o problema

**Comment by dinizime** [comment]
Testado, tudo ok!
