### ISSUE TITLE
Erro na ferramenta de seleção genérica 

### ISSUE THREAD

**Issue by dinizime** [lcoandrade/DsgTools#157]
### Subject of the issue (Assunto do problema)

Erro ao utilizar a ferramenta de seleção genérica em um local sem feições

`AttributeError: 'NoneType' object has no attribute 'intersects' 
Traceback (most recent call last):
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 135, in canvasPressEvent
    self.selectFeatures(e, hasControlModifyer = selected)
  File "C:/Users/Diniz/.qgis2/python/plugins\DsgTools\ProductionTools\CopyPasteTool\multiLayerSelect.py", line 191, in selectFeatures
    if feat.geometry().intersects(bbRect): #tests if feature intersects tool bounding box, otherwise skip it
AttributeError: 'NoneType' object has no attribute 'intersects'`

### Your environment (Seu ambiente)
* your operating system (Seu sistema operacional):  Windows 10
* version of QGIS (Versão do QGIS):  2.18.13
* version of DSGTools (Versão do DSGTools):  3.1_dev

**Comment by phborba** [comment]
Corrigido no commit 72b7dd6b30d0fe64795323f152d12207974d6ba5
