### ISSUE TITLE
Error warning after batch creation of spatialite databases from csv file

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#23]
After running batch creation of spatialite databases from csv file, the error windows pops up with the following content:

```
An error has occurred while executing Python code: 

Exception: {'m2260_2_no_CIF': "invalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''"} 
Traceback (most recent call last):
  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/DbTools/BatchDbCreator/createBatchFromCsv.py", line 83, in validatePage
    self.createDatabases(parameterDict)
  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/DbTools/BatchDbCreator/createBatchFromCsv.py", line 92, in createDatabases
    raise Exception(errorDict)
Exception: {'m2260_2_no_CIF': "invalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''\ninvalid literal for int() with base 10: ''"}


Python version: 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609] 
QGIS version: 2.14.5-Essen Essen, exported 
```

Obs.: The spatialite files are created and apparently without any issues.

**Comment by rsmaior** [comment]
The same exactly warning pops up when it comes to postgis database batch creation.

Here the content of the csv file:
```
m2216_4_ne_CIF 
m2216_2_ne_CIF 
m2216_2_se_CIF 
m2260_1_ne_CIF
m2260_2_no_CIF
```

**Comment by phborba** [comment]
try removing m from mis and _

These names should be:

2216-4-NE 
2216-2-NE 
2216-2-SE 
2260-1-NE
2260-2-NO

_CIF is supposed to be the sufix inserted by the interface
