### ISSUE TITLE
Error after loading db for validation

### ISSUE THREAD

**Issue by rsmaior** [lcoandrade/DsgTools#31]
Just loaded a db for validation and the following error appears:

```
An error has occurred while executing Python code: 

UnicodeEncodeError: 'ascii' codec can't encode characters in position 50-51: ordinal not in range(128) 
Traceback (most recent call last):
  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/CustomWidgets/earthCoverageWidget.py", line 55, in setDatabase
    self.loadEarthCoverage()
  File "/home/rodrigo/.qgis2/python/plugins/DsgTools/CustomWidgets/earthCoverageWidget.py", line 97, in loadEarthCoverage
    QgsMessageLog.logMessage(self.tr('Earth Coverage not loaded! Check log for details.')+str(e.args[0]), "DSG Tools Plugin", QgsMessageLog.CRITICAL)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 50-51: ordinal not in range(128)


Python version: 2.7.13 (default, Dec 21 2016, 07:16:46) [GCC 6.2.1 20160830] 
QGIS version: 2.14.7-Essen Essen, exported 

Python Path:
/usr/share/qgis/python/plugins/processing
/usr/share/qgis/python
/home/rodrigo/.qgis2/python
/home/rodrigo/.qgis2/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python27.zip
/usr/lib/python2.7
/usr/lib/python2.7/plat-linux2
/usr/lib/python2.7/lib-tk
/usr/lib/python2.7/lib-old
/usr/lib/python2.7/lib-dynload
/usr/lib/python2.7/site-packages
/usr/lib/python2.7/site-packages/gtk-2.0
/home/rodrigo/.qgis2//python
/home/rodrigo/.qgis2/python/plugins/DigitizingTools/tools
/home/rodrigo/.qgis2/python/plugins/DsgTools
/home/rodrigo/.qgis2/python/plugins/DsgTools/ProductionTools/CopyPasteTool
/usr/share/qgis/python/plugins/fTools/tools
```

**Comment by lcoandrade** [comment]
Borba already solve this problem...
