### ISSUE TITLE
BUG: Melhoramentos na ferramenta de gerenciamento de estilos

### ISSUE THREAD

**Issue by LEOXINGU** [lcoandrade/DsgTools#87]
A ferramenta de gerenciamento de estilos não funciona quando um Open Layer está aberto, por exemplo, o Google Hibrid.

**Comment by phborba** [comment]
Resolvido no commit 02718dcf4035aed96c67dfdbd91e777744ebf130 testa ae por gentileza

**Comment by LEOXINGU** [comment]
Continua sem funcionar por aqui.
Segue o Log:
Um erro ocorreu enquanto executava o código Python: 

AttributeError: 'OpenlayersLayer' object has no attribute 'dataProvider' 
Traceback (most recent call last):
  File "C:/Users/LEANDRO/.qgis2/python/plugins\DsgTools\ProductionTools\StyleManagerTool\styleManagerTool.py", line 178, in on_dbComboBox_currentIndexChanged
    abstractDb = self.getAbstractDb(dbName)
  File "C:/Users/LEANDRO/.qgis2/python/plugins\DsgTools\ProductionTools\StyleManagerTool\styleManagerTool.py", line 161, in getAbstractDb
    dbParameters, driverName = self.getParametersFromLyr(dbName)
  File "C:/Users/LEANDRO/.qgis2/python/plugins\DsgTools\ProductionTools\StyleManagerTool\styleManagerTool.py", line 143, in getParametersFromLyr
    candidateUri = QgsDataSourceURI(lyr.dataProvider().dataSourceUri())
AttributeError: 'OpenlayersLayer' object has no attribute 'dataProvider'


Versão do Python: 2.7.5 (default, May 15 2013, 22:44:16) [MSC v.1500 64 bit (AMD64)] 
Versão do QGIS: 2.14.11-Essen Essen, 2d09b0b

**Comment by phborba** [comment]
Blz, vou ver aqui e já dou o retorno

**Comment by phborba** [comment]
acho que resolvi no commit ca4602c20f112412c26a1d1299661ab522bab98a

**Comment by phborba** [comment]
Resolvido no pull request #122 do @LEOXINGU
